trigger:
- none

pool:
  vmImage: 'windows-latest'

steps:

# - task: vsts-chef-task-install-chefdk@1
#   inputs:
#     chefDKChannel: 'stable'

- task: chef-software.chef-azdo.install.component@3
  displayName: Install Chef Component
  inputs:
    component: chef-workstation

- task: CmdLine@2
  displayName: Install Chef PolicyFile
  inputs:
    script: 'C:\opscode\chef-workstation\bin\chef install'
    workingDirectory: '$(Build.Repository.LocalPath)/cookbooks/chef_chocolatey/'
  env:
    CHEF_LICENSE: accept
    PATH: C:\opscode\chef-workstation\bin\

- task: CmdLine@2
  displayName: Export Chef PolicyFile
  inputs:
    script: 'C:\opscode\chef-workstation\bin\chef export $(Build.Repository.LocalPath)/zero_repo'
    workingDirectory: '$(Build.Repository.LocalPath)/cookbooks/chef_chocolatey/'
  env:
    CHEF_LICENSE: accept
    PATH: C:\opscode\chef-workstation\bin\
    
- task: CmdLine@2
  displayName: Run Chef-Client
  inputs:
    script: 'C:\opscode\chef-workstation\bin\chef-client -z'
    workingDirectory: '$(Build.Repository.LocalPath)/zero_repo'
  env:
    CHEF_LICENSE: accept
    PATH: C:\opscode\chef-workstation\bin\
